version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-local
    restart: always
    ports:
      - '3137:3306'
    environment:
      MARIDADB_ROOT_PASSWORD: passwd
      MARIDADB_USER: user
      MARIDADB_PASSWORD: passwd
      MARIDADB_DATABASE: db
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: adminer-local
    ports:
      - '5138:8080'
    restart: always

volumes:
  mysql-data:
    driver: local
