version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-local
    ports:
      - '3137:3306'
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_USER: user
      MYSQL_PASSWORD: passwd
      MYSQL_DATABASE: db
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
